tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "primary": "#006591",
                "on-primary-fixed": "#001e2f",
                "on-tertiary": "#ffffff",
                "secondary-fixed-dim": "#3cddc7",
                "tertiary": "#576065",
                "surface-tint": "#006591",
                "error": "#ba1a1a",
                "surface-container-lowest": "#ffffff",
                "surface": "#f8f9ff",
                "tertiary-fixed": "#dbe4ea",
                "on-tertiary-fixed": "#141d21",
                "on-tertiary-container": "#2c3539",
                "secondary": "#006b5f",
                "on-error": "#ffffff",
                "surface-variant": "#d3e4fe",
                "surface-bright": "#f8f9ff",
                "surface-container-low": "#eff4ff",
                "surface-dim": "#cbdbf5",
                "on-secondary-container": "#007165",
                "on-secondary-fixed": "#00201c",
                "secondary-container": "#62fae3",
                "on-primary-fixed-variant": "#004c6e",
                "surface-container-high": "#dce9ff",
                "inverse-primary": "#89ceff",
                "primary-fixed": "#c9e6ff",
                "on-surface": "#0b1c30",
                "background": "#f8f9ff",
                "on-primary-container": "#003751",
                "on-background": "#0b1c30",
                "surface-container-highest": "#d3e4fe",
                "on-secondary": "#ffffff",
                "inverse-on-surface": "#eaf1ff",
                "tertiary-fixed-dim": "#bfc8ce",
                "primary-container": "#0ea5e9",
                "outline-variant": "#bec8d2",
                "secondary-fixed": "#62fae3",
                "outline": "#6e7881",
                "inverse-surface": "#213145",
                "tertiary-container": "#949da3",
                "on-secondary-fixed-variant": "#005047",
                "on-primary": "#ffffff",
                "error-container": "#ffdad6",
                "on-surface-variant": "#3e4850",
                "primary-fixed-dim": "#89ceff",
                "on-tertiary-fixed-variant": "#3f484d",
                "surface-container": "#e5eeff",
                "on-error-container": "#93000a"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "spacing": {
                "container-max": "1200px",
                "gutter": "24px",
                "lg": "48px",
                "margin-desktop": "auto",
                "xs": "4px",
                "xl": "80px",
                "margin-mobile": "16px",
                "base": "8px",
                "md": "24px",
                "sm": "12px"
            },
            "fontFamily": {
                "body-md": ["Inter"],
                "label-md": ["Inter"],
                "headline-lg-mobile": ["Plus Jakarta Sans"],
                "headline-md": ["Plus Jakarta Sans"],
                "headline-lg": ["Plus Jakarta Sans"],
                "body-lg": ["Inter"],
                "display-lg": ["Plus Jakarta Sans"],
                "label-sm": ["Inter"]
            },
            "fontSize": {
                "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
                "label-md": ["14px", { "lineHeight": "1.4", "letterSpacing": "0.01em", "fontWeight": "500" }],
                "headline-lg-mobile": ["28px", { "lineHeight": "1.3", "fontWeight": "600" }],
                "headline-md": ["24px", { "lineHeight": "1.4", "fontWeight": "600" }],
                "headline-lg": ["32px", { "lineHeight": "1.3", "fontWeight": "600" }],
                "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
                "display-lg": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
                "label-sm": ["12px", { "lineHeight": "1.4", "fontWeight": "600" }]
            }
        }
    }
};